# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 003ca71351dd93a87012773cf790a36271b0cece1552f23e3167a0cf65c65061704692b75106e3bb8538f44ec364366906ea5b11dce1ed44ba77145151ab3911

test:
  secret_key_base: 97670d4bdf5fcca58307861fdcc5907594c60dca9f620e4e39cb2cfbe8d6276063606f0de2c5020d203a8ba58361a4f5b906bcc1785aef328d2d7aae56356541

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
